//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class chen_add
    {
        public int id { get; set; }
        public Nullable<int> typeid { get; set; }
        public string title { get; set; }
        public string memo { get; set; }
        public string fenge { get; set; }
        public Nullable<int> width { get; set; }
        public Nullable<int> height { get; set; }
        public string classid { get; set; }
        public string ziduan { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<int> bitian { get; set; }
    }
}
