//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt_Contents
    {
        public int Id { get; set; }
        public string CallIndex { get; set; }
        public string Title { get; set; }
        public int ClassId { get; set; }
        public string Content { get; set; }
        public int SortId { get; set; }
        public string ver { get; set; }
        public string filepath { get; set; }
        public string ImgUrl { get; set; }
        public string ImgUrl2 { get; set; }
        public string Keyword { get; set; }
        public string Description { get; set; }
        public string Intro { get; set; }
        public string Herf { get; set; }
        public Nullable<int> HerfFlag { get; set; }
        public Nullable<int> IsLock { get; set; }
        public Nullable<int> Click { get; set; }
        public string content1 { get; set; }
        public string content2 { get; set; }
    }
}
