//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt_Channel
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public int ParentId { get; set; }
        public string ClassList { get; set; }
        public int ClassLayer { get; set; }
        public int SortId { get; set; }
        public string PageUrl { get; set; }
        public int KindId { get; set; }
        public string Content { get; set; }
        public string ImgUrl { get; set; }
        public string ver { get; set; }
        public string Filepath { get; set; }
        public string Keyword { get; set; }
        public string Description { get; set; }
        public string ImgUrl2 { get; set; }
        public string HtmlPath { get; set; }
        public string HtmlSize { get; set; }
        public string WebPath { get; set; }
        public string WebIndex { get; set; }
        public Nullable<int> LeftDisplay { get; set; }
        public Nullable<int> FrontDeskDisplay { get; set; }
        public string FileUrl { get; set; }
        public Nullable<int> IsNew { get; set; }
        public Nullable<int> IsSingle { get; set; }
        public Nullable<int> IsProduct { get; set; }
        public Nullable<int> IsRecruitment { get; set; }
        public Nullable<int> IsDownload { get; set; }
        public Nullable<int> IsLink { get; set; }
        public Nullable<int> IsLeaveMessage { get; set; }
        public Nullable<int> IsBanner { get; set; }
        public string PageType { get; set; }
        public Nullable<int> width { get; set; }
        public Nullable<int> height { get; set; }
        public Nullable<int> chen1 { get; set; }
        public Nullable<int> chen2 { get; set; }
    }
}
