//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt_Feedback
    {
        public int Id { get; set; }
        public int IsLock { get; set; }
        public System.DateTime AddTime { get; set; }
        public string ReContent { get; set; }
        public Nullable<System.DateTime> ReTime { get; set; }
        public Nullable<int> TypeId { get; set; }
        public string Ver { get; set; }
        public string UserName { get; set; }
        public string UserQQ { get; set; }
        public string UserTel { get; set; }
        public string Address { get; set; }
        public string Content { get; set; }
        public string UserSex { get; set; }
        public string MailBox { get; set; }
        public string OrderNumber { get; set; }
        public string Title { get; set; }
    }
}
