//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt_Job
    {
        public int id { get; set; }
        public string Title { get; set; }
        public Nullable<int> SortId { get; set; }
        public string Address { get; set; }
        public string JobType { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public string BeginTime { get; set; }
        public string EndTime { get; set; }
        public string People { get; set; }
        public string Education { get; set; }
        public string WorkYear { get; set; }
        public string Email { get; set; }
        public string Company { get; set; }
        public string Des { get; set; }
        public string Des1 { get; set; }
        public string Des2 { get; set; }
        public string Des3 { get; set; }
        public int classid { get; set; }
        public string Sex { get; set; }
        public int IsRed { get; set; }
        public int IsLock { get; set; }
        public string LinkUrl { get; set; }
        public string Field1 { get; set; }
        public string Filepath { get; set; }
        public Nullable<int> IsTop { get; set; }
        public string ver { get; set; }
        public Nullable<int> Click { get; set; }
        public string Keyword { get; set; }
        public string Description { get; set; }
        public string contact { get; set; }
        public string showemail { get; set; }
        public string tel { get; set; }
    }
}
