//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt_Links
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string UserName { get; set; }
        public string UserTel { get; set; }
        public string UserMail { get; set; }
        public string WebUrl { get; set; }
        public string ImgUrl { get; set; }
        public int IsImage { get; set; }
        public int SortId { get; set; }
        public int IsRed { get; set; }
        public int IsLock { get; set; }
        public System.DateTime AddTime { get; set; }
        public string ver { get; set; }
    }
}
