//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt_Member
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string UserEmail { get; set; }
        public string UserPhone { get; set; }
        public string UserGrade { get; set; }
        public string UserAddr { get; set; }
        public Nullable<int> UserAge { get; set; }
        public string UserBirth { get; set; }
        public string UserCompanyAddr { get; set; }
        public string UserSex { get; set; }
        public string UserPwd { get; set; }
        public string Ver { get; set; }
        public string Content { get; set; }
        public string Content1 { get; set; }
        public Nullable<int> IsRed { get; set; }
        public Nullable<int> IsLock { get; set; }
        public string Field1 { get; set; }
        public string Field2 { get; set; }
        public string Field3 { get; set; }
        public Nullable<int> UserIntegral { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public string UserCompanyPhone { get; set; }
        public string Job { get; set; }
        public Nullable<int> ClassId { get; set; }
    }
}
