//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt_Module
    {
        public int id { get; set; }
        public string ModuleName { get; set; }
        public string ModuleHref { get; set; }
        public Nullable<int> ModuleFid { get; set; }
        public Nullable<int> ModuleLock { get; set; }
        public string ModuleAlias { get; set; }
        public Nullable<int> order_id { get; set; }
        public string ver { get; set; }
    }
}
