//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt_Product
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public int ClassId { get; set; }
        public decimal Price { get; set; }
        public string ImgUrl { get; set; }
        public string Content { get; set; }
        public int Click { get; set; }
        public int IsMsg { get; set; }
        public int IsTop { get; set; }
        public int IsRed { get; set; }
        public int IsHot { get; set; }
        public int IsSlide { get; set; }
        public int IsLock { get; set; }
        public int SortId { get; set; }
        public System.DateTime AddTime { get; set; }
        public string document { get; set; }
        public string software { get; set; }
        public string Content1 { get; set; }
        public string Content2 { get; set; }
        public string Content3 { get; set; }
        public string ImgUrl1 { get; set; }
        public string Content4 { get; set; }
        public string ver { get; set; }
        public Nullable<int> Field1 { get; set; }
        public Nullable<int> Field2 { get; set; }
        public Nullable<int> Field3 { get; set; }
        public Nullable<int> Field4 { get; set; }
        public Nullable<int> Field5 { get; set; }
        public Nullable<int> Field6 { get; set; }
        public string Field7 { get; set; }
        public string Keyword { get; set; }
        public string Description { get; set; }
        public string ImgUrl2 { get; set; }
        public string ImgUrl3 { get; set; }
        public string Herf { get; set; }
        public Nullable<int> HerfFlag { get; set; }
        public string subTitle { get; set; }
        public string content5 { get; set; }
        public string htmlpath { get; set; }
        public string content6 { get; set; }
        public string content7 { get; set; }
        public string content8 { get; set; }
        public string content9 { get; set; }
        public string content10 { get; set; }
        public string content11 { get; set; }
        public string ImgUrl4 { get; set; }
        public string Zhaiyao1 { get; set; }
        public string Zhaiyao2 { get; set; }
        public string ImgUrl5 { get; set; }
        public string OnlineLink { get; set; }
    }
}
