//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt_productkey
    {
        public int id { get; set; }
        public Nullable<int> sortid { get; set; }
        public string subject { get; set; }
        public string content { get; set; }
        public string blinfo1 { get; set; }
        public string blinfo2 { get; set; }
        public string blinfo3 { get; set; }
        public string blinfo4 { get; set; }
        public string blinfo5 { get; set; }
        public string blinfo6 { get; set; }
        public string addtime { get; set; }
        public string ver { get; set; }
        public int classid { get; set; }
    }
}
