//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt_PicturesLink
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public int ClassId { get; set; }
        public string ImgUrl { get; set; }
        public string FilePath { get; set; }
        public Nullable<int> Click { get; set; }
        public string Content { get; set; }
        public Nullable<int> IsMsg { get; set; }
        public Nullable<int> IsLock { get; set; }
        public string ImgUrl2 { get; set; }
        public System.DateTime AddTime { get; set; }
        public Nullable<int> IsRed { get; set; }
        public string ver { get; set; }
        public Nullable<int> SortId { get; set; }
        public string SubTitle { get; set; }
    }
}
