//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt_SinglePage
    {
        public int Id { get; set; }
        public int Classid { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string ImgUrl { get; set; }
        public string ImgUrlSmall { get; set; }
        public int IsMsg { get; set; }
        public int IsTop { get; set; }
        public int IsRed { get; set; }
        public int IsHot { get; set; }
        public int IsSlide { get; set; }
        public int IsLock { get; set; }
        public System.DateTime AddTime { get; set; }
        public string Ver { get; set; }
        public Nullable<int> SortId { get; set; }
        public string Href { get; set; }
        public Nullable<int> HrefFalg { get; set; }
        public string HtmlPath { get; set; }
        public string SeoTitle { get; set; }
        public string SeoDescription { get; set; }
        public string SeoKeyWord { get; set; }
    }
}
