//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt_webset
    {
        public int id { get; set; }
        public string ver { get; set; }
        public string seoTitle { get; set; }
        public string seoKey { get; set; }
        public string seoDes { get; set; }
        public string tel { get; set; }
        public string fax { get; set; }
        public string links { get; set; }
        public string bhao { get; set; }
        public string htmlcontent { get; set; }
        public string other1 { get; set; }
        public string other2 { get; set; }
        public string other3 { get; set; }
    }
}
