//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt_Article
    {
        public int Id { get; set; }
        public int ClassId { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public string Form { get; set; }
        public string Keyword { get; set; }
        public string Description { get; set; }
        public string Daodu { get; set; }
        public string ImgUrl { get; set; }
        public string Content { get; set; }
        public int Click { get; set; }
        public int IsMsg { get; set; }
        public int IsTop { get; set; }
        public int IsRed { get; set; }
        public int IsHot { get; set; }
        public int IsSlide { get; set; }
        public int IsLock { get; set; }
        public System.DateTime AddTime { get; set; }
        public string ver { get; set; }
        public string filepath { get; set; }
        public Nullable<int> SortId { get; set; }
        public string Download { get; set; }
        public string SubTitle { get; set; }
        public string BigImgUrl { get; set; }
        public string IndexImgUrl { get; set; }
        public string Editor { get; set; }
        public string Herf { get; set; }
        public Nullable<int> HerfFlag { get; set; }
        public string htmlpath { get; set; }
        public string ImgUrl5 { get; set; }
        public string Spell { get; set; }
    }
}
