//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt_Bannner
    {
        public int Id { get; set; }
        public int ClassId { get; set; }
        public string Title { get; set; }
        public string Imgurl { get; set; }
        public string ImgurlSmallTitle { get; set; }
        public string ImgurlSmall { get; set; }
        public int Ismsg { get; set; }
        public int IsTop { get; set; }
        public int IsRed { get; set; }
        public int IsSlide { get; set; }
        public int IsLock { get; set; }
        public int SortId { get; set; }
        public System.DateTime AddTime { get; set; }
        public string Ver { get; set; }
        public string Description { get; set; }
        public string Herf { get; set; }
        public Nullable<int> HerfFlag { get; set; }
        public string HtmlPaht { get; set; }
        public string content1 { get; set; }
        public string content2 { get; set; }
    }
}
